version: '2.1'

services:
    server:
        build:
            context: docker
            dockerfile: Dockerfile-lab3
        privileged: true
        volumes:
            - ..:/elocal
        tty: true
        cap_add:
          - NET_ADMIN
          - NET_RAW
          - SYS_ADMIN
        networks:
            subnet2:
              ipv4_address: 198.10.0.2
        depends_on:
            - "router"
        command: /elocal/src/server.sh
    middle:
        build:
            context: docker
            dockerfile: Dockerfile-lab3
        volumes:
            - ..:/elocal
        tty: true
        cap_add:
          - NET_ADMIN
          - NET_RAW
          - SYS_ADMIN
        networks:
            subnet2:
              ipv4_address: 198.10.0.3
        depends_on:
            - "router"
        sysctls:
          - net.ipv4.ip_forward=1
        command: /elocal/src/server.sh
    router:
        build:
            context: docker
            dockerfile: Dockerfile-lab3
        volumes:
            - ..:/elocal
        tty: true
        cap_add:
          - NET_ADMIN
          - NET_RAW
          - SYS_ADMIN
        networks:
            subnet1:
              ipv4_address: 172.10.0.1
            subnet2:
              ipv4_address: 198.10.0.1
        sysctls:
          - net.ipv4.ip_forward=1
        #command: /elocal/src/drop_packages.sh
    client:
        build:
            context: docker
            dockerfile: Dockerfile-lab3
        volumes:
            - ..:/elocal
        tty: true
        cap_add:
          - NET_ADMIN
          - NET_RAW
          - SYS_ADMIN
        networks:
            subnet2:
              ipv4_address: 172.10.0.2
        depends_on:
            - "router"
            - "server"
        command: /elocal/src/client.sh
networks:
    subnet1:
        ipam:
            driver: default
            config:
                - subnet: 172.10.0.0/16
                  gateway: 172.10.1.1
    subnet2:
        ipam:
            driver: default
            config:
                - subnet: 198.10.0.0/16
                  gateway: 198.10.1.1
